# .github/workflows/release_drafter.yml

name: Release Drafter
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Release Drafter
        uses: release-drafter/release-drafter@v7
        with:
          config-file: .github/release-drafter.yml

      - name: Generate Changelog
        run: |
          git fetch --prune --unshallow
          release-drafter

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.release.tag_name }}
          release_name: Release ${{ github.event.release.tag_name }}
          files: |
            awesome-website.zip
            DEPLOY.md
          body: ${{ steps.generate-changelog.outputs.changelog }}
