# .github/workflows/u3_tarea5.yml

name: Continuous Deployment to Netlify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Hugo and dependencies
        run: |
          ./setup.sh

      - name: Lint
        run: |
          make lint

      - name: Build
        run: |
          make build

      - name: Deploy to Netlify Preview
        if: github.event_name == 'pull_request'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          netlify deploy --dir=./dist/ --json | tee deploy.json
          PREVIEW_URL=$(jq -r '.deploy_url' deploy.json)
          echo "Netlify Preview URL: $PREVIEW_URL"
          echo "::set-output name=preview_url::$PREVIEW_URL"
          netlify sites:list --json | jq -r '.[].site_id' | xargs -I {} netlify sites:delete {}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Deploy to Netlify Production
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          netlify deploy --prod --dir=./dist/
