name: u3_tarea0

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Ejecutar una vez al día a medianoche UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Install Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.81.0/hugo_extended_0.81.0_Linux-64bit.tar.gz
          tar -xzf hugo_extended_0.81.0_Linux-64bit.tar.gz
          sudo mv hugo /usr/local/bin/

      - name: Validate Makefile
        run: make help
